//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SirketOtomasyon2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Stok3Entities : DbContext
    {
        public Stok3Entities()
            : base("name=Stok3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Zimmet> tbl_Zimmet { get; set; }
        public virtual DbSet<tblGiris> tblGiris { get; set; }
        public virtual DbSet<tblParca> tblParca { get; set; }
        public virtual DbSet<tblPc> tblPc { get; set; }
        public virtual DbSet<tblPersonel> tblPersonel { get; set; }
    }
}
