//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SirketOtomasyon2
{
    using System;
    using System.Collections.Generic;
    
    public class tbl_Zimmet
    {
        public System.DateTime Tarih { get; set; }
        public int Yapan_Kisi_Id { get; set; }
        public Nullable<int> Yapilan_Kisi_No { get; set; }
        public Nullable<int> Parca_Id { get; set; }
        public Nullable<int> Pc_Id { get; set; }
        public string Not { get; set; }
    
      
    }
}
