//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SirketOtomasyon2
{
    using System;
    using System.Collections.Generic;
    
    public  class tblPc
    {
        public int Pc_Id { get; set; }
        public string Adi { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public string Firma { get; set; }
        public Nullable<System.DateTime> Alinan_Tarih { get; set; }
        public Nullable<int> Stok_Durumu { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string Not { get; set; }
    
      
    }
}
