//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SirketOtomasyon2
{
    using System;
    using System.Collections.Generic;
    
    public  class tblPersonel
    {
        public int Personel_No { get; set; }
        public Nullable<int> Kullanici_Id { get; set; }
        public string Kullanici_Tipi { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Adres { get; set; }
        public Nullable<decimal> Maas { get; set; }
        public Nullable<System.DateTime> Baslama_Tarihi { get; set; }
    
     
    }
}
